[tools]
sd = "latest"

# script/fenneldoc.lua needs a standalone Lua interpreter, luajit isn't enough.
lua = "5.4"

[tasks.fetch-fennel]
run = "bash script/fetch-fennel"

[tasks.render-api-documentation]
run = "script/render-api-documentation"

[tasks.setup-test-deps]
run = "bash ./script/setup-test-deps"

[tasks.test]
depends = ["setup-test-deps"]
run = "bash ./script/test"
